import enum


class Context(enum.Enum):
    MAIN_MENU = 1
    IN_GAME = 2
    PAUSE = 3
    OPTIONS = 4
    LOAD_SAVE = 5
    OPTIONS_WAITING_INPUT_UP = 5
    OPTIONS_WAITING_INPUT_DOWN = 6
    OPTIONS_WAITING_INPUT_LEFT = 7
    OPTIONS_WAITING_INPUT_RIGHT = 8
    OPTIONS_WAITING_INPUT_PAUSE = 9
    AUTO_PLAY = 10
