import enum


class Context(enum.Enum):
    MAIN_MENU = 1
    IN_GAME = 2
    DUAL_GAME = 3
    PAUSE = 4
    OPTIONS = 5
    LOAD_SAVE = 6
    OPTIONS_WAITING_INPUT_UP = 8
    OPTIONS_WAITING_INPUT_DOWN = 9
    OPTIONS_WAITING_INPUT_LEFT = 10
    OPTIONS_WAITING_INPUT_RIGHT = 11
    OPTIONS_WAITING_INPUT_PAUSE = 12
    OPTIONS_WAITING_INPUT_UP_SECOND = 13
    OPTIONS_WAITING_INPUT_DOWN_SECOND = 14
    OPTIONS_WAITING_INPUT_LEFT_SECOND = 15
    OPTIONS_WAITING_INPUT_RIGHT_SECOND = 16
    OPTIONS_WAITING_INPUT_PAUSE_SECOND = 17
