class Screen():
    WIDTH: int = 1280
    HEIGHT: int = 720
    SQUARE_SIZE: int = 15
    BOARD_HEIGHT: int = 40
    BOARD_WIDTH: int = 40
    BOARD_HEIGHT_DUAL: int = 40
    BOARD_WIDTH_DUAL: int = 80
    START_X: int = (WIDTH-(SQUARE_SIZE*BOARD_WIDTH))/2
    START_Y: int = (HEIGHT-(SQUARE_SIZE*BOARD_HEIGHT))/2
    START_X_DUAL: int = (WIDTH-(SQUARE_SIZE*BOARD_WIDTH_DUAL))/2
    START_Y_DUAL: int = (HEIGHT-(SQUARE_SIZE*BOARD_HEIGHT_DUAL))/2